projects:
  - id: kanbatte
    gitRepository: https://github.com/yuusoft-org/kanbatte.git

discord:
  users:
    - userId: 12345
      gitAuthor: Sample User <sample@example.com>
  servers:
    - name: Sample Server
      guildId: 56789
      channels:
        - projectId: kanbatte
          channelId: 1122334455
      allowedRoles:
        - 9876543210